### ISSUE TITLE
Unit test failed

### ISSUE THREAD

**Issue by lmulhall-phet** [phetsims/axon#178]
@samreid, sorry to add to your huge list of issues. CT has been orange or red since 9907ae0c48d075e1151fad29eab20614ff64303e.

CT gives the following:

```axon : top-level-unit-tests : require.js?ea
22 out of 23 tests passed. 1 failed.
Events: Basics failed:
Died on test #8     at https://bayes.colorado.edu/continuous-testing/snapshot-1527616776838/axon/js/EventsTests.js?bust=1527617678129:17:9
    at Object.execCb (https://bayes.colorado.edu/continuous-testing/snapshot-1527616776838/sherpa/lib/require-2.1.11.js:1650:25)
    at Module.check (https://bayes.colorado.edu/continuous-testing/snapshot-1527616776838/sherpa/lib/require-2.1.11.js:866:35)
    at Module.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1527616776838/sherpa/lib/require-2.1.11.js:1113:20)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1527616776838/sherpa/lib/require-2.1.11.js:132:17
    at https://bayes.colorado.edu/continuous-testing/snapshot-1527616776838/sherpa/lib/require-2.1.11.js:1156:11
    at each (https://bayes.colorado.edu/continuous-testing/snapshot-1527616776838/sherpa/lib/require-2.1.11.js:57:23): phetAllocation is not defined
ReferenceError: phetAllocation is not defined
    at Events.trigger (https://bayes.colorado.edu/continuous-testing/snapshot-1527616776838/axon/js/Events.js?bust=1527617678129:174:9)
    at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1527616776838/axon/js/EventsTests.js?bust=1527617678129:71:12)


Approximately 5/29/2018, 11:59:36 AM

**Comment by samreid** [comment]
@jonathanolson addressed this in https://github.com/phetsims/axon/commit/37d5839cf25343fec5811fefd088eeb510b8950b

Reassigned to @lmulhall-phet to make sure it clears up in the next round of CT.
