### ISSUE TITLE
CT no orderDependencies when starting

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/axon#295]
```
axon : top-level-unit-tests : unbuilt?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589811061330/axon/axon-tests.html?ea&brand=phet-io
48 out of 49 tests passed. 1 failed.
Property: Property.registerOrderDependency failed:
no orderDependencies when starting
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589811061330/axon/js/PropertyTests.js:263:12)

Property: Property.registerOrderDependency failed:
just added orderDependency
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589811061330/axon/js/PropertyTests.js:276:12)

Property: Property.registerOrderDependency failed:
failed, expected argument to be truthy, was: false
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589811061330/axon/js/PropertyTests.js:278:12)

Property: Property.registerOrderDependency failed:
dispose removes order dependency
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589811061330/axon/js/PropertyTests.js:281:12)

Property: Property.registerOrderDependency failed:
just added orderDependency from phetioDependencies
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589811061330/axon/js/PropertyTests.js:291:12)

Property: Property.registerOrderDependency failed:
failed, expected argument to be truthy, was: false
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589811061330/axon/js/PropertyTests.js:293:12)

Property: Property.registerOrderDependency failed:
dispose removes order dependency
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589811061330/axon/js/PropertyTests.js:296:12)

id: Bayes Chrome
Snapshot from 5/18/2020, 8:11:01 AM
```

**Comment by zepumph** [comment]
Thanks! Adding one test caused another test to fail because it was making an assumption about a global. I fixed both places by (a) cleaning up the new test to dispose and not leak into the global, and (b) for the older test in PropertyTests to not depend on the "clean slate" state of the global. Closing
