### ISSUE TITLE
CT: propertyStateHandlerSingleton tests for Property failed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#298]
Broken by phetsims/axon@7a42c26, see https://github.com/phetsims/phet-io/issues/1668#issuecomment-632987582.  I guess those unit tests are not being run by the pre-commit hook - should they be?

```
axon : top-level-unit-tests : unbuilt?brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/axon/axon-tests.html?brand=phet-io
50 out of 51 tests passed. 1 failed.
Property: propertyStateHandlerSingleton tests for Property failed:
Died on test #1 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/axon/js/PropertyTests.js:259:9: Property.registerPhetioOrderDependency is not a function
TypeError: Property.registerPhetioOrderDependency is not a function
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590203195335/axon/js/PropertyTests.js:275:14)

id: Bayes Chrome
Snapshot from 5/22/2020, 9:06:35 PM
```

**Comment by samreid** [comment]
Fixed as part of https://github.com/phetsims/phet-io/issues/1668#issuecomment-633087807, and verified on CT, closing.
