### ISSUE TITLE
CT propertyStateHandlerSingleton tests for Property failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/axon#300]
```
axon : top-level-unit-tests : unbuilt?brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590647133649/axon/axon-tests.html?brand=phet-io
50 out of 51 tests passed. 1 failed.
Property: propertyStateHandlerSingleton tests for Property failed:
failed, expected argument to be truthy, was: false
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590647133649/axon/js/PropertyTests.js:278:12)

Property: propertyStateHandlerSingleton tests for Property failed:
failed, expected argument to be truthy, was: false
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590647133649/axon/js/PropertyTests.js:293:12)

id: Bayes Chrome
Snapshot from 5/28/2020, 12:25:33 AM

----------------------------------

axon : top-level-unit-tests : unbuilt?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590647133649/axon/axon-tests.html?ea&brand=phet-io
50 out of 51 tests passed. 1 failed.
Property: propertyStateHandlerSingleton tests for Property failed:
failed, expected argument to be truthy, was: false
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590647133649/axon/js/PropertyTests.js:278:12)

Property: propertyStateHandlerSingleton tests for Property failed:
failed, expected argument to be truthy, was: false
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1590647133649/axon/js/PropertyTests.js:293:12)

id: Bayes Chrome
Snapshot from 5/28/2020, 12:25:33 AM
```

**Comment by zepumph** [comment]
Thanks! 

Looks like an issue where as a single test it passes, but other tests interfere with assumptions from inside the test. I updated it and things are passing now. Closing
