### ISSUE TITLE
CT order dependency between NumberProperty and its Range failed

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/axon#326]
```
axon : top-level-unit-tests : unbuilt?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597917199071/axon/axon-tests.html?ea&brand=phet-io
61 out of 62 tests passed. 1 failed.
PropertyStateHandler: Order dependency between NumberProperty and its Range failed:
Died on test #2 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597917199071/axon/js/PropertyStateHandlerTests.js:93:9: Assertion failed: isInStateScope is a required arg
Error: Assertion failed: isInStateScope is a required arg
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597917199071/assert/js/assert.js:22:13)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597917199071/phet-io/js/PhetioStateEngine.js:233:15)
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1597917199071/axon/js/PropertyStateHandlerTests.js:123:48)

id: Bayes Chrome
Snapshot from 8/20/2020, 3:53:19 AM
```

**Comment by zepumph** [comment]
Fixed in https://github.com/phetsims/axon/commit/a09c536c544271627845cdec60a23360df746593
