### ISSUE TITLE
Rename TimerType and timer

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#329]
From https://github.com/phetsims/phet-io/issues/1703#issuecomment-690675434

> If we rename timer=>stepTimer or simulationStepTimer then TimerType can be renamed Timer.js

**Comment by samreid** [comment]
Fixed and ready for review.

**Comment by pixelzoom** [comment]
Hmm...  I didn't realize that timer.js was a step timer.  That's now clear with the rename.  But then I have a potential problem in NS PlayButtonGroup:

```js
          stepTimer.runOnNextFrame( () => {
            addAMateButton.visible = ( bunnyCount === 1 );
            playButton.visible = ( bunnyCount > 1 );
          } );
```

This code assumes that it will be run _on the next next frame_, not on the next step.   And I think that's a valid assumption based on the name.    But now I see this (new?) documentation in stepTimer.js:

```js
... Only runs when the sim is active, during the step. ...
```

So 2 questions:
(1) Can we do something about this misleading `runOnNextFrame` name?
(2) How do I run something on the next frame, regardless of whether this sim is playing/paused.

**Comment by pixelzoom** [comment]
> (2) How do I run something on the next frame, regardless of whether this sim is playing/paused.

Looks like I should be using animationFrameTimer.js ?

**Comment by pixelzoom** [comment]
stepTimer.js doc says that it only runs "during the step".  Does "run" mean "emits"?  If that's the case, then I was expecting to see `stepTimer.emit` called only by Sim.js.  But I also see `stepTimer.emit` called by KeyStateTracker, Display, and UtteranceTests.  Can you clarify why those things are calling `stepTimer.emit`, and how that's "during the step"?

**Comment by zepumph** [comment]
I may be seeing some CT errors from this issue in built scenery libraries:

```
Fatal error: Converting circular structure to JSON

Webpack build errors: [ ModuleNotFoundError: Module not found: Error: Can't resolve './timer.js' in '/data/share/phet/continuous-testing/ct-snapshots/1599867498367/axon/js'
at factory.create (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/lib/Compilation.js:925:10)
at factory (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
at resolver (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
at asyncLib.parallel (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
at /data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/neo-async/async.js:2830:7
at /data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/neo-async/async.js:6877:13
at normalResolver.resolve (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
at doResolve (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:15:1)
at resolver.doResolve (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:15:1)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:27:1)
at resolver.doResolve (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn42 (<anonymous>:16:1)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:27:1)
at resolver.doResolve (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn1 (<anonymous>:16:1)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:15:1)
at fs.stat (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15)
at process.nextTick (/data/share/phet/continuous-testing/ct-snapshots/1599867498367/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15)
at process._tickCallback (internal/process/next_tick.js:61:11)

resolve './timer.js' in '/data/share/phet/continuous-testing/ct-snapshots/1599867498367/axon/js'
using description file: /data/share/phet/continuous-testing/ct-snapshots/1599867498367/axon/package.json (relative path: ./js)
Field 'browser' doesn't contain a valid alias configuration
using description file: /data/share/phet/continuous-testing/ct-snapshots/1599867498367/axon/package.json (relative path: ./js/timer.js)
no extension
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1599867498367/axon/js/timer.js doesn't exist
.wasm
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1599867498367/axon/js/timer.js.wasm doesn't exist
.mjs
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1599867498367/axon/js/timer.js.mjs doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1599867498367/axon/js/timer.js.js doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/1599867498367/axon/js/timer.js.json doesn't exist
as directory
/data/share/phet/continuous-testing/ct-snapshots/1599867498367/axon/js/timer.js doesn't exist ]
Snapshot from 9/11/2020, 3:38:18 PM
```

**Comment by pixelzoom** [comment]
Sounds like it's appropriate to replace "ready-for-review" with "blocks-publication".

**Comment by samreid** [comment]
Probably a casing problem, I'll take a look soon.

**Comment by samreid** [comment]
> (1) Can we do something about this misleading runOnNextFrame name?

I renamed it to `runOnNextTick`.

> Looks like I should be using animationFrameTimer.js ? Tracking in phetsims/natural-selection#227.

I commented in the issue.

> stepTimer.js doc says that it only runs "during the step".  Does "run" mean "emits"?  If that's the case, then I was expecting to see `stepTimer.emit` called only by Sim.js.  But I also see `stepTimer.emit` called by KeyStateTracker, Display, and UtteranceTests.  Can you clarify why those things are calling `stepTimer.emit`, and how that's "during the step"?

I updated the JSDoc in https://github.com/phetsims/axon/commit/09f16b8e072d9a5d05997ad860640c3085017209

> Probably a casing problem, I'll take a look soon.

I fixed the casing problem in the commits.

**Comment by pixelzoom** [comment]
Nice improvements, and thanks for the clarification.

**Comment by pixelzoom** [comment]
Is this issue blocking for the NS deliverable described in phetsims/natural-selection#208? Milestone for taking shas is this Thursday, 9/17.   Ideally this should be wrapped up, because the work has been done and is awaiting review.  But my opinion is not blocking, because it doesn't seem to causing any problems, and NS uses `stepTimer` in one place.

**Comment by zepumph** [comment]
@samreid, the changes look good to me! I like the rename to `runOnNextTick`. Nothing else here for me.

**Comment by samreid** [comment]
Thanks, closing.
