### ISSUE TITLE
CT: test EmitterIO failed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#378]
```
axon : top-level-unit-tests : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/axon/axon-tests.html
73 out of 74 tests passed. 1 failed.
EmitterIO: test EmitterIO failed:
Died on test #1 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:13:7: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:48:32)

id: Bayes Chrome
Snapshot from 3/8/2022, 3:34:05 AM

----------------------------------

axon : top-level-unit-tests : unbuilt?ea
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/axon/axon-tests.html?ea
71 out of 74 tests passed. 3 failed.
createObservableArray: Test constructor arguments failed:
should fail for invalid element types
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/createObservableArrayTests.js:618:27)

EmitterIO: test EmitterIO failed:
cannot emit string
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:37:27)

EmitterIO: test EmitterIO failed:
cannot emit string
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:38:27)

EmitterIO: test EmitterIO failed:
Died on test #5 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:13:7: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:48:32)
...
```

**Comment by zepumph** [comment]
Thanks for catching this. Emitter was not validating its arguments to emit() so many assert.throws() were incorrect. This also fixed a failing unit test for createObservableArray type validation.
