### ISSUE TITLE
CT cannot read properties of undefined reading 0

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/axon#379]
```
axon : top-level-unit-tests : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/axon/axon-tests.html
73 out of 74 tests passed. 1 failed.
EmitterIO: test EmitterIO failed:
Died on test #1 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:13:7: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:48:32)

id: Bayes Chrome
Snapshot from 3/8/2022, 3:34:05 AM

----------------------------------

axon : top-level-unit-tests : unbuilt?ea
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/axon/axon-tests.html?ea
71 out of 74 tests passed. 3 failed.
createObservableArray: Test constructor arguments failed:
should fail for invalid element types
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/createObservableArrayTests.js:618:27)

EmitterIO: test EmitterIO failed:
cannot emit string
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:37:27)

EmitterIO: test EmitterIO failed:
cannot emit string
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:38:27)

EmitterIO: test EmitterIO failed:
Died on test #5 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:13:7: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:48:32)

Emitter: Emitter Constructing and options failed:
Wrong number of emitting parameters
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:22:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type bool
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:25:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type string
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:28:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type undefined
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:31:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type null
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:34:12)

Emitter: Emitter Constructing and options failed:
Wrong number of emitting parameters, for e2
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:52:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type bool, for e2
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:55:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type string, for e2
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:58:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type undefined, for e2
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:61:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type null, for e2
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:64:12)

Emitter: Emitter Constructing and options failed:
Should catch second argument as wrong type
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:67:12)

Emitter: Emitter Constructing and options failed:
Should catch not enough arguments
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:70:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type undefined
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:86:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type undefined
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:89:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type 0
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:92:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type object
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:95:12)

id: Bayes Chrome
Snapshot from 3/8/2022, 3:34:05 AM

----------------------------------

axon : top-level-unit-tests : unbuilt?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/axon/axon-tests.html?ea&brand=phet-io
77 out of 80 tests passed. 3 failed.
createObservableArray: Test constructor arguments failed:
should fail for invalid element types
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/createObservableArrayTests.js:618:27)

EmitterIO: test EmitterIO failed:
cannot emit string
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:37:27)

EmitterIO: test EmitterIO failed:
cannot emit string
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:38:27)

EmitterIO: test EmitterIO failed:
Died on test #5 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:13:7: Cannot read properties of undefined (reading '0')
TypeError: Cannot read properties of undefined (reading '0')
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterIOTests.js:48:32)

Emitter: Emitter Constructing and options failed:
Wrong number of emitting parameters
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:22:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type bool
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:25:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type string
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:28:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type undefined
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:31:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type null
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:34:12)

Emitter: Emitter Constructing and options failed:
Wrong number of emitting parameters, for e2
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:52:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type bool, for e2
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:55:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type string, for e2
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:58:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type undefined, for e2
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:61:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type null, for e2
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:64:12)

Emitter: Emitter Constructing and options failed:
Should catch second argument as wrong type
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:67:12)

Emitter: Emitter Constructing and options failed:
Should catch not enough arguments
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:70:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type undefined
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:86:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type undefined
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:89:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type 0
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:92:12)

Emitter: Emitter Constructing and options failed:
Wrong parameter type object
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1646735645307/chipper/dist/js/axon/js/EmitterTests.js:95:12)

id: Bayes Chrome
Snapshot from 3/8/2022, 3:34:05 AM
```

**Comment by samreid** [comment]
This has been fixed for a while, closing.
