### ISSUE TITLE
CT: should forward after set to DerivedProperty after dependencies change

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/axon#405]
```
axon : top-level-unit-tests : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/axon/axon-tests.html
73 out of 74 tests passed. 1 failed.
TinyForwardingProperty: Basics failed:
should forward after set to DerivedProperty after dependencies change
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/chipper/dist/js/axon/js/TinyForwardingPropertyTests.js:34:10)

id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

axon : top-level-unit-tests : unbuilt?brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/axon/axon-tests.html?brand=phet-io
79 out of 80 tests passed. 1 failed.
TinyForwardingProperty: Basics failed:
should forward after set to DerivedProperty after dependencies change
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/chipper/dist/js/axon/js/TinyForwardingPropertyTests.js:34:10)

id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

axon : top-level-unit-tests : unbuilt?ea
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/axon/axon-tests.html?ea
73 out of 74 tests passed. 1 failed.
TinyForwardingProperty: Basics failed:
should forward after set to DerivedProperty after dependencies change
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/chipper/dist/js/axon/js/TinyForwardingPropertyTests.js:34:10)

id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM

----------------------------------

axon : top-level-unit-tests : unbuilt?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/axon/axon-tests.html?ea&brand=phet-io
79 out of 80 tests passed. 1 failed.
TinyForwardingProperty: Basics failed:
should forward after set to DerivedProperty after dependencies change
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1658457063507/chipper/dist/js/axon/js/TinyForwardingPropertyTests.js:34:10)

id: Bayes Puppeteer
Snapshot from 7/21/2022, 8:31:03 PM
```

**Comment by samreid** [comment]
Axon top level unit tests appear to be complete and clear in several recent columns.  Perhaps this issue can be closed.  @KatieWoe can you please double check?  Please close if CT seems clear on this problem.
