### ISSUE TITLE
CT: PropertyStateHandler: Order dependency between NumberProperty and its Range failed

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/axon#424]
Probably related to changes to NumberProperty rangeProperty that were made in https://github.com/phetsims/axon/issues/423.  This CT error seems to have started immediately after those changes were made:

```
axon : top-level-unit-tests : unbuilt?ea&brand=phet-io
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/axon/axon-tests.html?ea&brand=phet-io
94 out of 95 tests passed. 1 failed.
PropertyStateHandler: Order dependency between NumberProperty and its Range failed:
Died on test #2 at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/chipper/dist/js/axon/js/PropertyStateHandlerTests.js:73:9: Assertion failed: phetioID already registered: axon.test.rangeProperty
Error: Assertion failed: phetioID already registered: axon.test.rangeProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/assert/js/assert.js:28:13)
at PhetioEngine.phetioObjectAdded (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/chipper/dist/js/phet-io/js/phetioEngine.js:567:36)
at Object.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/chipper/dist/js/phet-io/js/phetioEngine.js:1018:20)
at Tandem.addPhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/chipper/dist/js/tandem/js/Tandem.js:145:36)
at Property.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/chipper/dist/js/tandem/js/PhetioObject.js:293:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/chipper/dist/js/tandem/js/PhetioObject.js:124:12)
at new ReadOnlyProperty (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/chipper/dist/js/axon/js/ReadOnlyProperty.js:96:5)
at new Property (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/chipper/dist/js/axon/js/Property.js:13:5)
at Object.<anonymous> (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1667521640987/chipper/dist/js/axon/js/PropertyStateHandlerTests.js:75:27)

id: Bayes Puppeteer
Snapshot from 11/3/2022, 6:27:20 PM
```

This is down in PhET-iO, and I don't understand what an "order dependency" is in the context of PropertyStateHandler.  So assigning to @zepumph and @samreid.

**Comment by samreid** [comment]
Fixed, closing.
