### ISSUE TITLE
CT cannot emit incorrect number

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/axon#438]
```
axon : top-level-unit-tests : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1684763871631/axon/axon-tests.html
93 out of 94 tests passed. 1 failed.
EmitterIO: test EmitterIO failed:
cannot emit incorrect number
at Object.<anonymous> (http://127.0.0.1/continuous-testing/ct-snapshots/1684763871631/chipper/dist/js/axon/js/EmitterIOTests.js:57:12)

[URL] http://127.0.0.1/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1684763871631%2Faxon%2Faxon-tests.html&testInfo=%7B%22test%22%3A%5B%22axon%22%2C%22top-level-unit-tests%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1684763871631%22%2C%22timestamp%22%3A1684764931046%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1684763871631%2Faxon%2Faxon-tests.html&testInfo=%7B%22test%22%3A%5B%22axon%22%2C%22top-level-unit-tests%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1684763871631%22%2C%22timestamp%22%3A1684764931046%7D
[NAVIGATED] about:blank
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1684763871631/axon/axon-tests.html
[CONSOLE] Failed to load resource: the server responded with a status of 404 (Not Found)
[CONSOLE] START: create
[CONSOLE] END: create

[CONSOLE] START: push hello
[CONSOLE] END: push hello

[CONSOLE] START: set element 0
[CONSOLE] END: set element 0

[CONSOLE] START: set element 5
[CONSOLE] END: set element 5

[CONSOLE] START: length = 0
[CONSOLE] END: length = 0

[CONSOLE] START: a,b,c
[CONSOLE] END: a,b,c

[CONSOLE] START: splice
[CONSOLE] END: splice

[CONSOLE] Time for 100000: 16 0.00016
[CONSOLE] Time for 100000: 24 0.00024
[CONSOLE] abcd
[CONSOLE] y x
[CONSOLE] z y
[CONSOLE] y x
[CONSOLE] a y
[CONSOLE] b a
[CONSOLE] z b
[CONSOLE] y x
[CONSOLE] a y
[CONSOLE] b a
[CONSOLE] z b
[CONSOLE] x
[CONSOLE] Variance number property tests:
[CONSOLE] Mean: 6
[CONSOLE] Standard deviation: 2
[CONSOLE] 8.168171920044545
[CONSOLE] 3.5186186356397577
[CONSOLE] 7.004412977741582
[CONSOLE] 8.297292650525211
[CONSOLE] 7.298714312984308
[CONSOLE] 6.7467175197890015
[CONSOLE] 9.542106551176417

id: "Sparky Node Puppeteer"
Snapshot from 5/22/2023, 7:57:51 AM

----------------------------------

axon : top-level-unit-tests : unbuilt
http://127.0.0.1/continuous-testing/ct-snapshots/1684763871631/axon/axon-tests.html
93 out of 94 tests passed. 1 failed.
EmitterIO: test EmitterIO failed:
cannot emit incorrect number
at Object.<anonymous> (http://127.0.0.1/continuous-testing/ct-snapshots/1684763871631/chipper/dist/js/axon/js/EmitterIOTests.js:57:12)

id: Sparky Puppeteer
Snapshot from 5/22/2023, 7:57:51 AM

----------------------------------

axon : top-level-unit-tests : unbuilt?brand=phet-io
http://127.0.0.1/continuous-testing/ct-snapshots/1684763871631/axon/axon-tests.html?brand=phet-io
99 out of 100 tests passed. 1 failed.
EmitterIO: test EmitterIO failed:
cannot emit incorrect number
at Object.<anonymous> (http://127.0.0.1/continuous-testing/ct-snapshots/1684763871631/chipper/dist/js/axon/js/EmitterIOTests.js:57:12)

[URL] http://127.0.0.1/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1684763871631%2Faxon%2Faxon-tests.html%3Fbrand%3Dphet-io&testInfo=%7B%22test%22%3A%5B%22axon%22%2C%22top-level-unit-tests%22%2C%22unbuilt%3Fbrand%3Dphet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1684763871631%22%2C%22timestamp%22%3A1684764824524%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1684763871631%2Faxon%2Faxon-tests.html%3Fbrand%3Dphet-io&testInfo=%7B%22test%22%3A%5B%22axon%22%2C%22top-level-unit-tests%22%2C%22unbuilt%3Fbrand%3Dphet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1684763871631%22%2C%22timestamp%22%3A1684764824524%7D
[NAVIGATED] about:blank
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1684763871631/axon/axon-tests.html?brand=phet-io
[CONSOLE] Failed to load resource: the server responded with a status of 404 (Not Found)
[CONSOLE] START: create
[CONSOLE] END: create

[CONSOLE] START: push hello
[CONSOLE] END: push hello

[CONSOLE] START: set element 0
[CONSOLE] END: set element 0

[CONSOLE] START: set element 5
[CONSOLE] END: set element 5

[CONSOLE] START: length = 0
[CONSOLE] END: length = 0

[CONSOLE] START: a,b,c
[CONSOLE] END: a,b,c

[CONSOLE] START: splice
[CONSOLE] END: splice

[CONSOLE] Time for 100000: 29 0.00029
[CONSOLE] Time for 100000: 17 0.00017
[CONSOLE] abcd
[CONSOLE] y x
[CONSOLE] z y
[CONSOLE] y x
[CONSOLE] a y
[CONSOLE] b a
[CONSOLE] z b
[CONSOLE] y x
[CONSOLE] a y
[CONSOLE] b a
[CONSOLE] z b
[CONSOLE] x
[CONSOLE] Variance number property tests:
[CONSOLE] Mean: 6
[CONSOLE] Standard deviation: 2
[CONSOLE] 8.26027625017288
[CONSOLE] 6.873417528247842
[CONSOLE] 5.9074012034544
[CONSOLE] 3.311010575710302
[CONSOLE] 4.82582550576052
[CONSOLE] 5.239765084355018
[CONSOLE] 7.676155624554854

id: "Sparky Node Puppeteer"
Snapshot from 5/22/2023, 7:57:51 AM

----------------------------------

axon : top-level-unit-tests : unbuilt?brand=phet-io
http://127.0.0.1/continuous-testing/ct-snapshots/1684763871631/axon/axon-tests.html?brand=phet-io
99 out of 100 tests passed. 1 failed.
EmitterIO: test EmitterIO failed:
cannot emit incorrect number
at Object.<anonymous> (http://127.0.0.1/continuous-testing/ct-snapshots/1684763871631/chipper/dist/js/axon/js/EmitterIOTests.js:57:12)

[URL] http://127.0.0.1/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1684763871631%2Faxon%2Faxon-tests.html%3Fbrand%3Dphet-io&testInfo=%7B%22test%22%3A%5B%22axon%22%2C%22top-level-unit-tests%22%2C%22unbuilt%3Fbrand%3Dphet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1684763871631%22%2C%22timestamp%22%3A1684767272533%7D
[NAVIGATED] http://127.0.0.1/continuous-testing/aqua/html/qunit-test.html?url=..%2F..%2Fct-snapshots%2F1684763871631%2Faxon%2Faxon-tests.html%3Fbrand%3Dphet-io&testInfo=%7B%22test%22%3A%5B%22axon%22%2C%22top-level-unit-tests%22%2C%22unbuilt%3Fbrand%3Dphet-io%22%5D%2C%22snapshotName%22%3A%22snapshot-1684763871631%22%2C%22timestamp%22%3A1684767272533%7D
[NAVIGATED] about:blank
[NAVIGATED] http://127.0.0.1/continuous-testing/ct-snapshots/1684763871631/axon/axon-tests.html?brand=phet-io
[CONSOLE] Failed to load resource: the server responded with a status of 404 (Not Found)
[CONSOLE] START: create
[CONSOLE] END: create

[CONSOLE] START: push hello
[CONSOLE] END: push hello

[CONSOLE] START: set element 0
[CONSOLE] END: set element 0

[CONSOLE] START: set element 5
[CONSOLE] END: set element 5

[CONSOLE] START: length = 0
[CONSOLE] END: length = 0

[CONSOLE] START: a,b,c
[CONSOLE] END: a,b,c

[CONSOLE] START: splice
[CONSOLE] END: splice

[CONSOLE] Time for 100000: 10 0.0001
[CONSOLE] Time for 100000: 8 0.00008
[CONSOLE] abcd
[CONSOLE] y x
[CONSOLE] z y
[CONSOLE] y x
[CONSOLE] a y
[CONSOLE] b a
[CONSOLE] z b
[CONSOLE] y x
[CONSOLE] a y
[CONSOLE] b a
[CONSOLE] z b
[CONSOLE] x
[CONSOLE] Variance number property tests:
[CONSOLE] Mean: 6
[CONSOLE] Standard deviation: 2
[CONSOLE] 7.789146869689651
[CONSOLE] 5.266021468496697
[CONSOLE] 9.73209257963562
[CONSOLE] 11.85428016532917
[CONSOLE] 5.00355107885822
[CONSOLE] 4.870911699271187
[CONSOLE] 5.471571887003923

id: "Sparky Node Puppeteer"
Snapshot from 5/22/2023, 7:57:51 AM
```

**Comment by samreid** [comment]
@zepumph and I fixed it in the commit, closing.
