### ISSUE TITLE
Consider rewriting Property using Emitter

### ISSUE THREAD

**Issue by samreid** [phetsims/axon#82]
At the Dec 17 meeting, we wondered what it would look like for Property to be implemented using Emitter instead of its own custom emitter-like implementation.

**Comment by samreid** [comment]
This change is fairly straightforward and in the end, trades a slice (for safe array copy in Property) for a push/pop (in Emitter).  I guess (but am not sure) this will be a net win for CPU usage & garbage collection.  I'm running the simulation fuzz tests to catch any edge cases.

**Comment by samreid** [comment]
Tagging @pixelzoom and @jessegreenberg so they are aware of this upcoming change, please see above.

**Comment by samreid** [comment]
Axon unit tests are all passing.

**Comment by samreid** [comment]
Here's the full list of assertions when running the requirejs fuzz tests:

```
Sim errors (dev):

area-builder
Uncaught TypeError: Cannot read property 'forEach' of undefined
TypeError: Cannot read property 'forEach' of undefined
    at ShapePlacementBoard.inherit.removeTaggedObservers (http://localhost/area-builder/js/common/model/ShapePlacementBoard.js?bust=1450384349490:336:26)
    at http://localhost/area-builder/js/common/model/ShapePlacementBoard.js?bust=1450384349490:548:14
    at Array.forEach (native)
    at ObservableArray.inherit.forEach (http://localhost/axon/js/ObservableArray.js?bust=1450384349490:308:27)
    at ShapePlacementBoard.inherit.releaseAllShapes (http://localhost/area-builder/js/common/model/ShapePlacementBoard.js?bust=1450384349490:547:27)
    at ExploreNode.addChild.EraserButton.listener (http://localhost/area-builder/js/explore/view/ExploreNode.js?bust=1450384349490:114:50)
    at http://localhost/sun/js/buttons/PushButtonModel.js?bust=1450384349490:130:9
    at Array.forEach (native)
    at PushButtonModel.inherit.fire (http://localhost/sun/js/buttons/PushButtonModel.js?bust=1450384349490:129:12)
    at http://localhost/sun/js/buttons/PushButtonModel.js?bust=1450384349490:73:25

bending-light
Uncaught Error: Assertion failed: Segment end is infinite
Error: Assertion failed: Segment end is infinite
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:23:13)
    at Subpath.inherit.addSegmentDirectly (http://localhost/kite/js/util/Subpath.js?bust=1450384567676:105:17)
    at Subpath.inherit.addSegment (http://localhost/kite/js/util/Subpath.js?bust=1450384567676:122:14)
    at Shape.inherit.addSegmentAndBounds (http://localhost/kite/js/Shape.js?bust=1450384567676:805:29)
    at Shape.inherit.lineToPoint (http://localhost/kite/js/Shape.js?bust=1450384567676:147:14)
    at new LightRay (http://localhost/bending-light/js/common/model/LightRay.js?bust=1450384567676:124:10)
    at IntroModel.inherit.addAndAbsorb (http://localhost/bending-light/js/intro/model/IntroModel.js?bust=1450384567676:280:27)
    at IntroModel.inherit.propagateRays (http://localhost/bending-light/js/intro/model/IntroModel.js?bust=1450384567676:240:20)
    at IntroModel.inherit.updateModel (http://localhost/bending-light/js/common/model/BendingLightModel.js?bust=1450384567676:120:14)
    at http://localhost/bending-light/js/intro/model/IntroModel.js?bust=1450384567676:91:18

charges-and-fields
Uncaught Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:23:13)
    at Display.extend.ensureNotPainting (http://localhost/scenery/js/display/Display.js?bust=1450384767473:1058:17)
    at BackboneDrawable.inherit.markDirtyDrawable (http://localhost/scenery/js/display/BackboneDrawable.js?bust=1450384767473:211:22)
    at WebGLBlock.inherit.markDirty (http://localhost/scenery/js/display/Drawable.js?bust=1450384767473:282:31)
    at WebGLBlock.inherit.markDirtyDrawable (http://localhost/scenery/js/display/WebGLBlock.js?bust=1450384767473:249:12)
    at WebGLNodeDrawable.inherit.markDirty (http://localhost/scenery/js/display/Drawable.js?bust=1450384767473:282:31)
    at ElectricPotentialGridWebGLNode.inherit.invalidatePaint (http://localhost/scenery/js/nodes/WebGLNode.js?bust=1450384767473:103:30)
    at ElectricPotentialGridWebGLNode.inherit.addParticle (http://localhost/charges-and-fields/js/charges-and-fields/view/ElectricPotentialGridWebGLNode.js?bust=1450384767473:116:14)
    at ElectricPotentialGridWebGLNode.inherit.addAllParticles (http://localhost/charges-and-fields/js/charges-and-fields/view/ElectricPotentialGridWebGLNode.js?bust=1450384767473:104:16)
    at ElectricPotentialGridWebGLNode.inherit.paintWebGLDrawable (http://localhost/charges-and-fields/js/charges-and-fields/view/ElectricPotentialGridWebGLNode.js?bust=1450384767473:360:16)
charges-and-fields
Uncaught Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:23:13)
    at Display.extend.ensureNotPainting (http://localhost/scenery/js/display/Display.js?bust=1450384767473:1058:17)
    at BackboneDrawable.inherit.markDirtyDrawable (http://localhost/scenery/js/display/BackboneDrawable.js?bust=1450384767473:211:22)
    at SVGBlock.inherit.markDirty (http://localhost/scenery/js/display/Drawable.js?bust=1450384767473:282:31)
    at SVGBlock.inherit.markDirtyDrawable (http://localhost/scenery/js/display/SVGBlock.js?bust=1450384767473:165:12)
    at PathSVGDrawable.inherit.markDirty (http://localhost/scenery/js/display/Drawable.js?bust=1450384767473:282:31)
    at PathSVGDrawable.proto.markPaintDirty (http://localhost/scenery/js/nodes/Path.js?bust=1450384767473:341:14)
    at PathSVGDrawable.PaintableStatefulDrawable.proto.markDirtyFill (http://localhost/scenery/js/nodes/Paintable.js?bust=1450384767473:959:14)
    at Path.invalidateFill (http://localhost/scenery/js/nodes/Paintable.js?bust=1450384767473:790:32)
    at Path.extend.setFill (http://localhost/scenery/js/nodes/Paintable.js?bust=1450384767473:111:18)
charges-and-fields
Uncaught Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
Error: Assertion failed: This should not be run in the call tree of updateDisplay(). If you see this, it is likely that either the last updateDisplay() had a thrown error and it is trying to be run again (in which case, investigate that error), OR code was run/triggered from inside an updateDisplay() that has the potential to cause an infinite loop, e.g. CanvasNode paintCanvas() call manipulating another Node, or a bounds listener that Scenery missed.
    at window.assertions.assertFunction (http://localhost/assert/js/assert.js:23:13)
    at Display.extend.ensureNotPainting (http://localhost/scenery/js/display/Display.js?bust=1450384767473:1058:17)
    at BackboneDrawable.inherit.markDirtyDrawable (http://localhost/scenery/js/display/BackboneDrawable.js?bust=1450384767473:211:22)
    at SVGBlock.inherit.markDirty (http://localhost/scenery/js/display/Drawable.js?bust=1450384767473:282:31)
    at SVGBlock.inherit.markDirtyGroup (http://localhost/scenery/js/display/SVGBlock.js?bust=1450384767473:159:12)
    at SVGGroup.inherit.markDirty (http://localhost/scenery/js/display/SVGGroup.js?bust=1450384767473:122:20)
    at SVGGroup.inherit.markVisibilityDirty (http://localhost/scenery/js/display/SVGGroup.js?bust=1450384767473:154:14)
    at HighlightNode.Events.trigger0 (http://localhost/axon/js/Events.js?bust=1450384767473:282:29)
    at HighlightNode.extend.setVisible (http://localhost/scenery/js/nodes/Node.js?bust=1450384767473:2442:14)
    at HighlightNode.visible (http://localhost/scenery/js/nodes/Node.js?bust=1450384767473:2446:33)
```

It looks like only the 1st issue is attributable to the Property changes.  Area-builder was using a private Property field.

**Comment by samreid** [comment]
After changing area-builder to use the new internal Property structure, it is passing fuzz test.  I'll take another quick look through before committing.  After commit, it would be good for another developer to take a look since this is a fundamental data structure used widely in our sims.

**Comment by samreid** [comment]
Change committed above, @jessegreenberg are you available to perform a micro-review?

**Comment by samreid** [comment]
Something is suspicious, axon tests failing now... I'll look into it.

**Comment by samreid** [comment]
Fixed above, ready for review again, @jessegreenberg are you available to perform a micro-review?

**Comment by jessegreenberg** [comment]
Changes involving use of Emitter.js look good to me @samreid.  I notice two things worth discussing:

1. ```this.changedEmitter``` is marked as ``` @public (unit-tests)```.  Does this mean:
   * "Private except for the functions required by unit tests" or
   *  "Public, heavily used by functions in unit tests" ?
   - If it means the first Item, I might prefer ```@private (unit-tests)``` to mark private for all code other than unit tests.

2.  @pixelzoom had changed ```Emitter.containsListener``` to ```Emitter.isListener``` in commit fe3b65dfc633cacd425faace965b987d59d58e46, to match Node.isChild().  I notice that it was changed back in commit a7940fa67f38e82fc761ab7eede706f4e3b3958e.  After reviewing Emitter.js code, containsListener seems to fit the function better, but we may want to discuss this.

Back to @samreid for further discussion.

**Comment by samreid** [comment]
@jessegreenberg thanks for this review.  Indeed I meant `@private (unit-tests)`, nice catch.  Regarding the isListener thanks for pointing this out, I was not aware that this was a recent change.  I originally started with `isListener` but in context it seemed very confusing:

```js
emitter.isListener(x); // This sounds like we are asking if the emitter is some kind of listener.
```

I suppose I would have the same confusion about `Node.isChild`

```js
a.isChild(b);  // Seems confusing, like we may be asking whether a is b's child.
```

The method names that I think work best for both of these cases are `containsX` or `hasX`, or at least some verb that refers to the object the method is being invoked on.

**Comment by samreid** [comment]
Fixed the public/private annotation above.  @pixelzoom and @jonathanolson should weigh in on the naming of the methods, since they were both involved.  I'll unassign for now, with a `developer-meeting` label in case @pixelzoom @jonathanolson @jessegreenberg and I cannot work things out before the next developer meeting.

**Comment by pixelzoom** [comment]
The change to `isListener` was vetted at 12/17/2015 developer meeting, see https://github.com/phetsims/axon/commit/fe3b65dfc633cacd425faace965b987d59d58e46. Looks like you explicitly changed it back to `containsListener` in https://github.com/phetsims/axon/commit/a7940fa67f38e82fc761ab7eede706f4e3b3958e.

`containsListener` implies that Emitter is a container (not the case) or uses a container to store listeners (breaks semantic encapsulation).   I'd be OK with `hasListener`, but that has potential to cause confusion with `hasListeners`.

Looking at other similar APIs... axon.Property has no equivalent functions (should it?) axon.Events has `hasListener`, but no `hasListeners`.  It would be nice if APIs with similar functionality used similar function names.

**Comment by jessegreenberg** [comment]
My favorite is ```hasListener```, but I can appreciate the possibility for confusion with ```hasListeners```.  Accidentally calling
```js
a.hasListeners( b );
```
would be tricky to catch because ```hasListeners``` will also return a boolean without failure.
Could we catch this with something like
```js
assert && assert( arguments.length === 0, 'hasListeners should have no arguments, did you mean hasListener?' );
```

**Comment by samreid** [comment]
`hasListener` sounds great to me.  I'm not too concerned about mixing up hasListener/hasListeners, but if others are concerned I think @jessegreenberg's suggestion will solve that problem.  (Could also put a similar assertion in hasListener.)

**Comment by pixelzoom** [comment]
+1 for assertions in hasListener and hasListeners.

**Comment by samreid** [comment]
@jonathanolson prefers changing isChild to hasChild in scenery as well.

**Consensus: `has` sounds preferable to `is`**

@samreid will create a scenery issue for renaming isChild to hasChild.

**Comment by samreid** [comment]
@jonathanolson said if it is easy to do global query replace (across axon and scenery), ok to do so.

**Comment by samreid** [comment]
I'm seeing 0 occurrences of isListener across our repos.  I renamed `containsListener` to `hasListener`.  I added assertions into both `hasListener` and `hasListeners`.  Axon unit tests are passing.  Bending Light is launching and running without exceptions.  Will commit shortly.

**Comment by samreid** [comment]
Fix committed above.  I'll create a separate issue for scenery and reassign this one to @pixelzoom for review at his discretion.

**Comment by pixelzoom** [comment]
Looks good, closing.
